# Generated by Django 3.0.8 on 2020-09-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("star_wars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="people",
            options={"verbose_name_plural": "People"},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name_plural": "Species"},
        ),
    ]
