# Generated by Django 3.0.8 on 2020-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("star_wars", "0002_auto_20200907_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="mass",
            field=models.CharField(max_length=5),
        ),
    ]
